# Generated by Django 4.2.3 on 2023-11-23 18:41

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cat_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="ijh",
                        unique=True,
                    ),
                ),
                ("cat_title", models.CharField(max_length=100)),
                (
                    "cat_image_file",
                    models.ImageField(
                        default="", max_length=999, upload_to="main/images/cat_image"
                    ),
                ),
                ("cat_image_url", models.URLField(default="", max_length=300)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
    ]
