# Generated by Django 5.0.1 on 2024-03-01 18:12

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_payment_status_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=order.models.generate_unique_order_id, max_length=50, unique=True),
        ),
    ]
