# Generated by Django 5.0.1 on 2024-03-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_userprofile_user_phone'),
        ('order', '0006_rename_total_price_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.useraddress'),
        ),
    ]
