# Generated by Django 4.2.3 on 2023-12-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="Product",
            new_name="product",
        ),
    ]
