# Generated by Django 5.0.1 on 2024-03-01 17:36

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=cart.models.generate_unique_cart_id, max_length=50, unique=True),
        ),
    ]
