# Generated by Django 4.2.5 on 2023-11-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_pfp',
            field=models.ImageField(upload_to='images'),
        ),
    ]
