# Generated by Django 4.2.5 on 2023-11-08 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', shortuuid.django_fields.ShortUUIDField(alphabet='abdefgh12345', length=10, max_length=20, prefix='', unique=True)),
                ('prod_title', models.CharField(default='new_product', max_length=100)),
                ('prod_desc', models.TextField(blank=True, default='No description added for this product!', null=True)),
                ('prod_price', models.DecimalField(decimal_places=2, default='1.99', max_digits=10)),
                ('prod_old_price', models.DecimalField(decimal_places=2, default='2.99', max_digits=10)),
                ('prod_specs', models.TextField(blank=True, null=True)),
                ('prod_instock', models.BooleanField(default=True)),
                ('prod_date_added', models.DateTimeField(auto_now_add=True)),
                ('prod_date_updated', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
