# Generated by Django 4.2.5 on 2023-11-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_old_price',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
        ),
    ]
