# Generated by Django 4.2.5 on 2023-11-08 05:17

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_prod_id_alter_product_prod_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ijklmno6789', length=22, max_length=20, prefix='ijh', unique=True),
        ),
    ]
