# Generated by Django 4.2.5 on 2023-11-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_prod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_pfp',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
