# Generated by Django 4.2.5 on 2023-11-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userprofile_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_pfp',
            field=models.ImageField(upload_to='images'),
        ),
    ]
