# Generated by Django 4.2.5 on 2023-11-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userprofile_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(default='', upload_to='products/'),
        ),
    ]
