# Generated by Django 4.2.5 on 2023-11-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default='', upload_to='main/images/cat_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(default='', upload_to='main/images/prod_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_pfp',
            field=models.ImageField(default='', upload_to='main/images/user_pfp'),
        ),
    ]
