# Generated by Django 4.2.5 on 2023-11-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_category_cat_image_alter_product_prod_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default='', max_length=999, upload_to='main/images/cat_image'),
        ),
    ]
