# Generated by Django 4.2.5 on 2023-11-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_category_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
