# Generated by Django 4.2.5 on 2023-11-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
