# Generated by Django 4.2.3 on 2023-11-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_product_prod_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="prod_image",
            field=models.ImageField(
                default="", max_length=999, upload_to="main/images/prod_image"
            ),
        ),
    ]
