# Generated by Django 4.2.3 on 2023-11-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_product_prod_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="cat_image",
            new_name="cat_image_file",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="prod_image",
            new_name="prod_image_file",
        ),
        migrations.AddField(
            model_name="category",
            name="cat_image_url",
            field=models.URLField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="product",
            name="prod_image_url",
            field=models.URLField(default="", max_length=300),
        ),
    ]
