# Generated by Django 4.2.3 on 2023-11-23 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_rename_cat_image_category_cat_image_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="prod_date_updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
