# Generated by Django 4.2.3 on 2023-11-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_product_prod_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_pfp_url",
            field=models.URLField(default="", max_length=300),
        ),
    ]
