# Generated by Django 4.2.3 on 2023-11-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_userprofile_user_pfp_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
