# Generated by Django 4.2.3 on 2023-11-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_useraddress_delete_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="city",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="country",
            field=models.CharField(default="India", max_length=50),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="postal_code",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="state",
            field=models.CharField(default="", max_length=50),
        ),
    ]
