# Generated by Django 4.2.3 on 2023-11-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_useraddress_city_alter_useraddress_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
